(()=>{'use strict';const M=window.MR,V=window.MR_VIEW,S=()=>M.state,t=k=>M.tx(k),$=q=>document.querySelector(q),modal=$('#modal'),mb=$('#modalBody');
const saveRender=()=>{M.save();V.render()};const toast=x=>{const n=$('#toast');n.textContent=x;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),1800)};
function open(html){mb.innerHTML=html;modal.hidden=false}function close(){modal.hidden=true;mb.innerHTML=''}
function assignModal(worker=''){open(`<h2>${t('assign')}</h2><div class="form-grid"><label class="label">${t('chooseWorker')}<select id="aw" class="select">${S().workers.map(w=>`<option value="${w.id}" ${w.id===worker?'selected':''}>${w.name}</option>`).join('')}</select></label><label class="label">${t('course')}<select id="ac" class="select"><option value="course1">${t('course1')}</option><option value="course2">${t('course2')}</option><option value="course3">${t('course3')}</option></select></label><label class="label">${t('due')}<input id="ad" type="date" class="input" value="2026-08-15"></label><div class="actions"><button class="btn" data-action="close">${t('cancel')}</button><button class="btn primary" data-action="save-assign">${t('save')}</button></div></div>`)}
function assign(){const w=$('#aw').value,title=$('#ac').value,due=$('#ad').value,id='A-'+Date.now();S().assignments.push({id,worker:w,title,due,progress:0,step:0,done:false,quiz:null});close();saveRender();toast(t('notify'))}
function approve(w){if(!w.identity||!w.refresher||!w.task||!w.orientation||w.notice!==S().noticeVersion||w.hold){toast(t('notApproved'));return}w.approved=true;saveRender();toast(t('saved'))}
function exportCsv(){const rows=[['worker_id','name','employer','role','work_order','status','checked_in'],...S().workers.map(w=>[w.id,w.name,w.employer,w.role,w.workOrder,M.status(w),w.checked])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='mineready-workforce.csv';a.click();URL.revokeObjectURL(a.href)}
function importCsv(file){const r=new FileReader();r.onload=()=>{try{const lines=String(r.result).trim().split(/\r?\n/),head=lines.shift().split(',').map(x=>x.replaceAll('"','').trim().toLowerCase());for(const line of lines){const c=line.match(/("[^"]*(?:""[^"]*)*"|[^,]+)/g)?.map(x=>x.replace(/^"|"$/g,'').replaceAll('""','"'))||[];const o=Object.fromEntries(head.map((h,i)=>[h,c[i]||'']));if(!o.worker_id||S().workers.some(w=>w.id===o.worker_id))continue;S().workers.push({id:o.worker_id,name:o.name||o.worker_id,face:M.F.carlos,employer:o.employer||'Imported Contractor',role:o.role||'Worker',crew:o.crew||'Crew',workOrder:o.work_order||'Pending',identity:false,refresher:false,task:false,orientation:false,notice:0,approved:false,hold:false,checked:false})}saveRender();toast(t('saved'))}catch(e){toast('CSV error')}};r.readAsText(file)}
function submitQuiz(){const a=S().assignments.find(x=>x.id===S().courseAssignment);if(!a)return;const ok=[0,1,2].every(i=>document.querySelector(`input[name=q${i}]:checked`)?.value==='ok')&&$('#ack')?.checked&&$('#signature')?.value.trim();a.quiz=ok?'passed':'failed';if(ok){a.done=true;a.progress=100;const w=M.W(a.worker);if(a.title==='course2')w.refresher=true;if(a.title==='course3')w.task=true;if(a.title==='course1'){w.orientation=true;w.notice=S().noticeVersion}w.approved=false;toast(t('passed'));S().page='home'}else toast(t('failed'));saveRender()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){S().page=b.dataset.page;saveRender();return}if(b.dataset.lang){S().lang=b.dataset.lang;saveRender();return}if(b.dataset.role){S().role=b.dataset.role;S().page=b.dataset.role==='worker'?'home':'today';saveRender();return}if(b.dataset.gate){S().active=b.dataset.gate;S().page='gate';saveRender();return}if(b.dataset.assign){assignModal(b.dataset.assign);return}if(b.dataset.startCourse){const a=S().assignments.find(x=>x.id===b.dataset.startCourse);S().active=a.worker;S().courseAssignment=a.id;S().page='course';a.progress=Math.max(a.progress,10);saveRender();return}const a=b.dataset.action,w=a&&b.dataset.id?M.W(b.dataset.id):null;if(a==='close')close();if(a==='assign')assignModal();if(a==='save-assign')assign();if(a==='approve')approve(w);if(a==='checkin'){w.checked=true;saveRender();toast(t('checkIn'))}if(a==='checkout'){w.checked=false;saveRender();toast(t('checkOut'))}if(a==='hold'){w.hold=true;w.approved=false;saveRender()}if(a==='removeHold'){w.hold=false;saveRender()}if(a==='export')exportCsv();if(a==='import')$('#csvFile')?.click();if(a==='reset'){localStorage.removeItem('mineready-recovery-v1');location.reload()}if(a==='course-next'){const x=S().assignments.find(x=>x.id===S().courseAssignment);x.step=Math.min(3,(x.step||0)+1);x.progress=Math.min(80,x.step*25);saveRender()}if(a==='course-back'){const x=S().assignments.find(x=>x.id===S().courseAssignment);if(x.step>0){x.step--;saveRender()}else{S().page='training';saveRender()}}if(a==='course-submit')submitQuiz()});
document.addEventListener('change',e=>{if(e.target.id==='gateSelect'){S().active=e.target.value;saveRender()}if(e.target.id==='csvFile'&&e.target.files[0])importCsv(e.target.files[0])});
document.addEventListener('input',e=>{if(e.target.id==='search'){const q=e.target.value.toLowerCase();document.querySelectorAll('#peopleList .worker-row').forEach(n=>n.hidden=!n.textContent.toLowerCase().includes(q))}});modal.addEventListener('click',e=>{if(e.target===modal)close()});window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(console.warn);V.render();
})();
