(()=>{'use strict';
const M=window.MR, e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), t=k=>M.tx(k), S=()=>M.state;
const icon=n=>({today:'◫',gate:'⌁',people:'●',training:'▶',home:'⌂',pass:'▦',reports:'≡'}[n]||'•');
const nav=()=>{const role=S().role,pages=role==='mine'?[['today','today'],['gate','gate'],['people','people'],['training','training']]:role==='employer'?[['today','today'],['people','people'],['training','training'],['reports','reports']]:[['home','home'],['training','training'],['pass','workerPass'],['profile','profile']];return `<div class="desktop-nav">${pages.map(([p,k])=>`<button data-page="${p}" class="${S().page===p?'active':''}">${icon(p)} ${t(k)}</button>`).join('')}</div><nav class="bottom-nav">${pages.map(([p,k])=>`<button data-page="${p}" class="${S().page===p?'active':''}">${icon(p)}<br>${t(k)}</button>`).join('')}</nav>`};
const top=()=>`<header class="topbar"><div class="brand"><div class="mark">09</div><div><strong>MineReady</strong><small>${t('site')}</small></div></div><div class="top-spacer"></div><div class="seg"><button data-lang="en" class="${S().lang==='en'?'active':''}">EN</button><button data-lang="es" class="${S().lang==='es'?'active':''}">ES</button></div><div class="seg role-switch"><button data-role="mine" class="${S().role==='mine'?'active':''}">${t('mine')}</button><button data-role="employer" class="${S().role==='employer'?'active':''}">${t('employer')}</button><button data-role="worker" class="${S().role==='worker'?'active':''}">${t('worker')}</button></div></header>`;
const hero=(h,p)=>`<div class="hero"><div><span class="role-pill">${t(S().role)}</span><h1>${h}</h1><p>${p}</p></div><span class="badge"><i class="dot"></i>${t('demo')}</span></div>`;
const pill=w=>`<span class="status ${M.status(w)}">${t(M.status(w))}</span>`;
const avatar=w=>`<img class="avatar" src="${w.face}" alt="">`;
const blockerText=w=>M.blocker(w)?t(M.blocker(w)):t('approved');
const row=(w,buttons='')=>`<div class="worker-row">${avatar(w)}<div><h3>${e(w.name)}</h3><div class="meta">${e(w.employer)} · ${e(w.role)}<br>${t('workOrder')}: ${e(w.workOrder)} · ${e(w.crew)}</div></div><div>${pill(w)}${buttons}</div></div>`;
const stats=()=>{const ws=S().workers;return `<div class="grid stats">${[[ws.length,'expected'],[ws.filter(w=>M.status(w)==='ready').length,'ready'],[ws.filter(w=>['blocked','pending','hold'].includes(M.status(w))).length,'blocked'],[ws.filter(w=>w.checked).length,'onSite']].map(x=>`<div class="card stat"><strong>${x[0]}</strong><span>${t(x[1])}</span></div>`).join('')}</div>`};
function mineToday(){const bad=S().workers.filter(w=>M.status(w)!=='ready');return `${hero(t('today'),t('exceptions'))}${stats()}<div class="grid two"><section><div class="section-head"><div><h2>${t('exceptions')}</h2><p>${bad.length?bad.length+' '+t('blocked'):t('allClear')}</p></div><button class="btn primary small" data-page="gate">${t('openGate')}</button></div><div class="worker-list">${bad.map(w=>row(w,`<br><button class="btn small" data-gate="${w.id}">${t('openGate')}</button>`)).join('')||`<div class="card empty">${t('allClear')}</div>`}</div></section><aside><div class="section-head"><h2>${t('notice')}</h2></div><div class="card notice"><strong>${t('notice')}</strong><p>${t('noticeBody')}</p></div><div class="section-head"><h2>${t('onSite')}</h2></div><div class="worker-list">${S().workers.filter(w=>w.checked).map(w=>row(w)).join('')||`<div class="card empty">0 ${t('onSite')}</div>`}</div></aside></div>`}
const checks=w=>[['identity',w.identity],['refresher',w.refresher],['task',w.task],['orientation',w.orientation],['currentNotice',w.notice===S().noticeVersion],['mineApproval',w.approved]].map(([k,v])=>`<div class="check ${v?'':'bad'}"><i>${v?'✓':'!'}</i>${t(k)}</div>`).join('');
function gate(){const w=M.W(S().active)||S().workers[0],ok=M.status(w)==='ready';return `${hero(t('gate'),t('approved'))}<div class="grid two"><section class="card"><label class="label">${t('chooseWorker')}<select class="select" id="gateSelect">${S().workers.map(x=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>${e(x.name)} · ${x.id}</option>`).join('')}</select></label><div class="gate-card">${avatar(w)}<h2>${e(w.name)}</h2><div class="meta">${e(w.employer)} · ${e(w.workOrder)}</div><div class="big-status" style="color:${ok?'var(--green)':'var(--amber)'}">${ok?t('approved'):t('notApproved')}</div><p class="meta">${blockerText(w)}</p><div class="checks">${checks(w)}</div><div class="actions">${!w.approved&&!w.hold?`<button class="btn primary" data-action="approve" data-id="${w.id}">${t('approve')}</button>`:''}${ok?`<button class="btn primary" data-action="${w.checked?'checkout':'checkin'}" data-id="${w.id}">${t(w.checked?'checkOut':'checkIn')}</button>`:''}<button class="btn ${w.hold?'':'danger'}" data-action="${w.hold?'removeHold':'hold'}" data-id="${w.id}">${t(w.hold?'removeHold':'hold')}</button></div></div></section><aside><div class="section-head"><h2>${t('people')}</h2></div><div class="worker-list">${S().workers.map(x=>row(x,`<br><button class="btn small" data-gate="${x.id}">${t('gate')}</button>`)).join('')}</div></aside></div>`}
function people(){return `${hero(t('people'),t('expected'))}<div class="toolbar"><input id="search" class="input search" placeholder="${t('search')}"><button class="btn" data-action="import">${t('import')}</button><button class="btn" data-action="export">${t('export')}</button><input id="csvFile" type="file" accept=".csv" hidden></div><div class="section-head"><h2>${t('people')}</h2></div><div id="peopleList" class="worker-list compact">${S().workers.map(w=>row(w, S().role==='employer'?`<br><button class="btn small" data-assign="${w.id}">${t('assign')}</button>`:'')).join('')}</div>`}
const assignmentCard=(a)=>{const w=M.W(a.worker),pct=a.done?100:a.progress||0;return `<div class="card course"><div class="status ${a.done?'ready':a.progress?'pending':'blocked'}">${t(a.done?'completed':a.progress?'inProgress':'assigned')}</div><h3>${t(a.title)}</h3><div class="meta">${e(w.name)} · ${t('due')}: ${e(a.due)}</div><div class="progress"><i style="width:${pct}%"></i></div>${S().role==='worker'&&!a.done?`<button class="btn primary" data-start-course="${a.id}">${t(a.progress?'continue':'start')}</button>`:''}</div>`};
function training(){const list=S().role==='worker'?S().assignments.filter(a=>a.worker===S().active):S().assignments;return `${hero(t('training'),t('myTraining'))}${S().role!=='worker'?`<button class="btn primary" data-action="assign">${t('assign')}</button>`:''}<div class="section-head"><h2>${t('training')}</h2></div><div class="grid three">${list.map(assignmentCard).join('')||`<div class="card empty">${t('allClear')}</div>`}</div>`}
function employerToday(){const pending=S().assignments.filter(a=>!a.done);return `${hero(t('today'),t('employer'))}${stats()}<div class="section-head"><div><h2>${t('training')}</h2><p>${pending.length} ${t('pending')}</p></div><button class="btn primary small" data-action="assign">${t('assign')}</button></div><div class="grid three">${pending.map(assignmentCard).join('')||`<div class="card empty">${t('allClear')}</div>`}</div>`}
function reports(){return `${hero(t('reports'),t('status'))}<div class="grid stats"><div class="card stat"><strong>${S().assignments.length}</strong><span>${t('assigned')}</span></div><div class="card stat"><strong>${S().assignments.filter(a=>a.done).length}</strong><span>${t('completed')}</span></div><div class="card stat"><strong>${S().workers.filter(w=>w.checked).length}</strong><span>${t('onSite')}</span></div><div class="card stat"><strong>${S().workers.filter(w=>M.status(w)==='ready').length}</strong><span>${t('ready')}</span></div></div><div class="section-head"><h2>${t('reports')}</h2></div><div class="actions"><button class="btn" data-action="export">${t('export')}</button><button class="btn" data-action="reset">Reset demo</button></div>`}
function workerHome(){const w=M.W(S().active);return `${hero(t('home'),t('showAtGate'))}<div class="grid two"><div class="card pass">${avatar(w)}<h2>${e(w.name)}</h2><p class="meta">${e(w.employer)} · ${e(w.role)}</p><div class="big-status" style="color:${M.status(w)==='ready'?'var(--green)':'var(--amber)'}">${M.status(w)==='ready'?t('approved'):t('notApproved')}</div><p>${blockerText(w)}</p><button class="btn primary" data-page="pass">${t('workerPass')}</button></div><div><div class="section-head"><h2>${t('myTraining')}</h2></div><div class="grid">${S().assignments.filter(a=>a.worker===w.id).map(assignmentCard).join('')||`<div class="card empty">${t('allClear')}</div>`}</div></div></div>`}
function qr(id){let h=[...id].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0),x='';for(let i=0;i<169;i++){h=(h*1664525+1013904223)|0;x+=`<span class="${((h>>>28)&1)||i<3||i%13<2?'on':''}"></span>`}return x}
function pass(){const w=M.W(S().active);return `${hero(t('workerPass'),t('showAtGate'))}<div class="card pass" style="max-width:460px;margin:auto">${avatar(w)}<h2>${e(w.name)}</h2><div class="meta">${e(w.employer)}<br>${t('workOrder')}: ${e(w.workOrder)}</div><div class="big-status" style="color:${M.status(w)==='ready'?'var(--green)':'var(--amber)'}">${M.status(w)==='ready'?t('approved'):t('notApproved')}</div><div class="qr" aria-label="Worker QR">${qr(w.id)}</div><strong>${w.id}</strong><p class="meta">${blockerText(w)}</p></div>`}
function profile(){const w=M.W(S().active);return `${hero(t('profile'),t('worker'))}<div class="card" style="max-width:620px"><div class="worker-row">${avatar(w)}<div><h3>${e(w.name)}</h3><div class="meta">${w.id}<br>${e(w.employer)}</div></div>${pill(w)}</div><div class="section-head"><h2>${t('lang')}</h2></div><div class="seg" style="width:max-content"><button data-lang="en" class="${S().lang==='en'?'active':''}">English</button><button data-lang="es" class="${S().lang==='es'?'active':''}">Español</button></div></div>`}
function lesson(){const a=S().assignments.find(x=>x.id===S().courseAssignment),step=a?.step||0,lessons=['lesson1','lesson2','lesson3'];if(!a)return training();if(step<3)return `${hero(t(a.title),t('training'))}<div class="card lesson"><span class="status pending">${t('training')} ${step+1}/3</span><h2>${t(lessons[step])}</h2><p>${t('noticeBody')}</p><ul><li>${t('refresher')}</li><li>${t('task')}</li><li>${t('currentNotice')}</li></ul><div class="actions"><button class="btn" data-action="course-back">${t('back')}</button><button class="btn primary" data-action="course-next">${t('next')}</button></div></div>`;return quiz(a)}
function quiz(a){const done=a.quiz;return `${hero(t('question'),t(a.title))}<div class="card lesson"><h2>${t('question')}</h2>${[['q1','a1'],['q2','a2'],['q3','a3']].map((q,i)=>`<div><p><strong>${i+1}. ${t(q[0])}</strong></p><label class="quiz-option"><input type="radio" name="q${i}" value="ok">${t(q[1])}</label><label class="quiz-option"><input type="radio" name="q${i}" value="bad">${S().lang==='es'?'Una opción incorrecta':'An incorrect option'}</label></div>`).join('')}<label class="label">${t('sign')}<input class="input" id="signature" value="${e(M.W(a.worker).name)}"></label><label class="quiz-option"><input id="ack" type="checkbox">${t('ack')}</label>${done?`<div class="status ${done==='passed'?'ready':'blocked'}">${t(done)}</div>`:''}<div class="actions"><button class="btn" data-action="course-back">${t('back')}</button><button class="btn primary" data-action="course-submit">${t('finish')}</button></div></div>`}
function render(){const role=S().role,p=S().page;let body;if(p==='course')body=lesson();else if(role==='mine')body=p==='gate'?gate():p==='people'?people():p==='training'?training():mineToday();else if(role==='employer')body=p==='people'?people():p==='training'?training():p==='reports'?reports():employerToday();else body=p==='training'?training():p==='pass'?pass():p==='profile'?profile():workerHome();document.documentElement.lang=S().lang;document.getElementById('app').innerHTML=`<div class="shell">${top()}<main class="layout">${nav()}${body}</main></div>`}
window.MR_VIEW={render,row,assignmentCard};
})();
